# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-aac7aa7d-5d69-4084-bb16-06cb3cb77d43";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-aac7aa7d-5d69-4084-bb16-06cb3cb77d43".device =
    "/dev/disk/by-uuid/aac7aa7d-5d69-4084-bb16-06cb3cb77d43";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CBCB-F030";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-3315d2a5-77b5-4ca1-b516-3715f606ce18"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
