name: build-system
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        hostname:
          - workstation

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7
      - name: "Free Disk Space"
        uses: wimpysworld/nothing-but-nix@main
      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v31

      - name: "Build ${{ matrix.hostname }} NixOS config 🛠️"
        run: |
          nix run github:Mic92/nix-fast-build -- --skip-cached --flake .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel
