name: update-flake-lock
on:
  workflow_dispatch: # Allow manual triggering
  schedule:
    - cron: '0 3 * * 6' # Run every saturday

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v31

      - name: "Patch flake"
        run: |
          sed -i 's/submodules = true;/submodules = false;/' flake.nix
      - name: "Update flake.lock"
        id: update
        uses: DeterminateSystems/update-flake-lock@v28
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          commit-msg: "Update flake.lock"
          pr-title: "Update flake.lock"
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

      - name: "Print PR number"
        run: echo "Pull request number is ${{ steps.update.outputs.pr_number }}"
